/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bjjrurbqwuuhxnoxpwzs"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqanJ1cmJxd3V1aHhub3hwd3pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2MDcxMjgsImV4cCI6MjA3NzE4MzEyOH0.sMZ9evF99MseCjEaGPCw4gh5APccI5YS-orFI3mr0-o"